
services:
    frontend:
      build: webFrontEnd
      container_name: fe
      ports:
        - "3000:80"  
      depends_on:
        - backend


    database:
      image: 'mysql'
      container_name: 'DB'
      ports:
        - "3366:3306"
      volumes:
        - mysql_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DBpassword}
        MYSQL_DATABASE: ${DBname}
        # MYSQL_USER: root
        MYSQL_PASSWORD: ${DBpassword}
        

    backend:
      container_name: be
      build: threetier
      # command: "python manage.py runserver 0.0.0.0:8000"
      # command: >
      #     sh -c "sleep 2 &&
      #         python manage.py migrate --noinput &&
      #         python manage.py runserver 0.0.0.0:8000"
      command: "python manage.py runserver 0.0.0.0:8000"
      restart: always
      ports:
        - "8000:8000"
      environment:
        DBname : ${DBname}
        DBpassword : ${DBpassword}
        DBport : ${DBport}
        DBhost : ${DBhost}
      depends_on:
        - database

volumes:
  mysql_data:
