FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE = 1
ENV PYTHONUNBUFFERED = 1

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt
COPY . .

# ENV DBhost="localhost"
# ENV DBname="loc"
# ENV DBuser="root"
# ENV DBpassword="Muthuraman1#"
# ENV DBport="3306"
RUN python manage.py makemigrations
RUN python manage.py migrate



# EXPOSE 8000
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
